### ISSUE TITLE
Bug: Crash on Launch

### ISSUE THREAD

**Issue by s-ayush2903** [prudhvir3ddy/DailyBugle#5]
**Bug Description**
When the app is launched, it crashes due to some NPE. 

Following is the ss of logcat:
![log](https://user-images.githubusercontent.com/56556919/77805387-c4185600-70a7-11ea-9709-ac995063955f.png)

Supporting Visuals
![issue](https://user-images.githubusercontent.com/56556919/77805558-2f622800-70a8-11ea-8a1c-3954162dfd6f.gif)

**Comment by prudhvir3ddy** [comment]
@s-ayush2903 that's because you haven't set up the app key.


check-in the readme about  how to  set up the key

**Comment by prudhvir3ddy** [comment]
still, the app shouldn't crash. thanks for the issue

**Comment by s-ayush2903** [comment]
> @s-ayush2903 that's because you haven't set up the app key.
> 
> check-in the readme about how to set up the key

No, the absence of key does not cause this. It solely occurs due to NPE and nothing else.
As in the corresponding PR opened, the API key is still not present and though the app launches smoothly(after the npe is fixed).

**Comment by prudhvir3ddy** [comment]
you are getting no internet screen because of it

**Comment by s-ayush2903** [comment]
Is there any discussion room regarding the project?

**Comment by prudhvir3ddy** [comment]
> Is there any discussion room regarding the project?

no. you can discuss in here

**Comment by s-ayush2903** [comment]
> > Is there any discussion room regarding the project?
> 
> no. you can discuss in here

Can we extend di in the module?
And one more thing, what is the motto of the app?

**Comment by prudhvir3ddy** [comment]
@s-ayush2903 no motto, just to show everyone how to build a standard app
